### ISSUE TITLE
ItemManager가 item을 crud하는 과정에서 csv 파일을 생성하도록 수정

### ISSUE THREAD

**Issue by miiiingi** [miiiingi/VEDA_MiniProject1#16]
## 기능 구현
- [x] ItemManager가 item을 crud하는 과정에서 csv 파일을 생성하도록 수정 -> 메인 메뉴에 save, load CSV 콘솔을 추가하여 이를 수행할 수 있도록함.

## 테스트 케이스
- [x] csv와 db모두 잘 동작하는지 확인 필요

**Comment by KevinJYLee** [comment]
dev/15 에서 customerManager 클래스에 대해 작업했던 load 및 save 절차에 대한 방향성은 아래와 같습니다..
- load from CSV 는 파일이름을 매개변수로 받아, 동작 전 db 와 map 을 초기화한 후 -> CSV 내용물에만 의존하도록 db 와 map 에 다시 데이터를 입력한다.
- save to SCV 는 파일 이름을 매개변수로 받아, 단순히 db 에서 각 행의 값들 읽어온 후 .csv 파일에 작성합니다. 

mainMenu 에서 customer CSV 파일이름은 customerList.csv 로 했습니다.
