### ISSUE TITLE
상품 클래스 및 상품 매니저 클래스 생성

### ISSUE THREAD

**Issue by miiiingi** [miiiingi/VEDA_MiniProject1#3]
## 기능 구현
- [x] 상품 매니저 클래스 작성
- [x] 상품 CRUD 메소드 작성
- [x] 상품 클래스 작성
- [x] 상품 CRUD와 데이터 베이스 간의 연동 작업

## 테스트 케이스
- [x] 상품 CRUD가 잘 동작하는가 ? 
- [x] 상품 CRUD가 데이터 베이스와 잘 연동이 되는가 ?

**Comment by KevinJYLee** [comment]
피드백 드립니다 !

- item 클래스에 대해 전방참조 테크닉을 활용하려고 하신 것 같습니다. 이를 위해 Item.h 에 대한 include 는 생략하는 것이 맞지 않나요?
	- unordered_map 은 템플릿 클래스이기 때문에 반드시 Item.h 가 include 되어야 하지 않나? 싶긴 하지만 customerManger 클래스를 작성함에 있어서 같은 경우에도 저는 customer.h 를 직접 include 없이 전방참조만 하였음에도 컴파일에 이상이 없었던 기억이 있습니다.

- .cpp 파일에서는, .h 파일에 include 된 라이브러리들이 굳이 다시 include 되지 않고 있습니다. 이 부분 chatGPT 에게 문의했을 때, 의존성에 관해 탐색하는 시간이 길어지는 게 오히려 컴파일 타임이 길어지는 결과를 낳는다고 하더군요.(즉 chatGPT 는 .cpp 파일에선 사용되는 라이브러리들은 중복이어도 굳이 include 를 또 해주는 쪽이 권장된다고 하는것입니다.) 이게 특히 전방참조 테크닉이랑 다소 충돌하는 이야기인지라, 이 부분은 우선 개인 재량에 맡기고 강사님께 여쭙는게 어떨까 싶습니다. 

팀작업 피드백 - 코드

- 우선 제가 sqlite3 를 사용을 많이 안해본지라, 해당 라이브러리의 자세한 사용에 대해선 제대로 이해하고 피드백 하려면 라이브러리 함수들에 대한 공부가 필요합니다. 중간에 SQL 구문이 const char*  에 문자열 형태로 전달이 되던데, 특히 이런게 제가 피드백이 불가합니다 …(SQL 문법이든, 해당 문자열을 활용한 _exec 함수의 사용에 대한 것이든..)

- 개발 환경에 따라 unordered_map 을 헤더파일에서 선언하는 상황의 유니크포인터랑 맵이랑 템플릿 닫는 꺾새가 연속되면서, “>>” 라고 적히는 부분이 컴파일 에러가 나는 경우가 있습니다. 제가 vim 에서 사용하는 g++ 은 해당 오류가 없는지라 customerManager.h 에서는 해당 부분이 그대로 “>>” 라고 적혀 있습니다. 그런데 민기님은 “std::unordered_map<std::string, std::unique_ptr<Item> > ItemMap;” 과 같이 꺾새 사이를 띄우셨더라구요. 아마 이 부분이 컴파일 에러의 원인일 수 있습니다. 만약 이게 문제라면 어느 쪽이던 합의가 필요할 듯 하네요.

- 유니크포인터 사용하기 때문에, 컴파일이 반드시 C++14 or 그 이후의 표준으로 이루어져야 합니다.

- unordered_map 에 사용에 있어서, 신규 데이터를 입력함에 있어 저는 customerMamager 에서 map 클래스의 insert 함수를 쓰고 민기님은 “[]” 연산자를 활용하고 계십니다. Insert 는 중복 key 에 대해 요소 삽입을 하지 않고, [] 는 중복 key 에 대해 덮어쓰기를 한다는 차이점이 있네요. 민기님 코드는 앞서 바코드에 대해 find 함수로 중복체크를 하고 계서서 사실상 동작상의 큰 차이는 저는 없다고 봅니다. 오히려 효율적인 코드라고 생각해요.

- 143 행 이후의 내용에 대해 : map 에 존재하지 않지만, sql 에는 존재하는 바코드에 대한 대응으로 보입니다. 새로 생성해서 map 에 만들어주고 find 작업은 작업대로 실행하는 듯 보이네요. 혹시 근데, 43행 addItem 코드에서 SQL & map 에 모두 추가되지 않고 SQL 에만 Item 이 추가되어 있는 예외케이스가 존재하나요? 그렇지 않다면 find 함수는 가장 위의 it->second.get() & 검색 실패한 상황에 대한 방어코드 정도로 충분해 보입니다.

- 민기님 코드에서 종종 데이터를 읽는 상황에 대해서 item 에 대해 유니크포인터가 아니라 원시코드를 get() 함수를 통해 받아서 사용합니다. 저도 좀 이쪽으로 코드를 수정해야하나 싶은 생각이 드네요. 

- sqlite3_bind_int 가 arm64 에 대해 뭐 Undefined 라는 에러가 좀 보이는데..해당 내용은 아래 이미지 확인하시고 한번 트라이해보시길 바랍니다.

- waring 이 세개 뜨는데, item.h 라고 실제 파일 이름이 있으나 헤더파일 include 는 대문자 I 를 써서 Item 이라고 되어 있네요 ㅎ 

<img width="539" alt="image" src="https://github.com/user-attachments/assets/f4eafb2a-4c9e-4aef-9760-80bc569579f4">
