### ISSUE TITLE
CustomerManager 기능 추가 구현

### ISSUE THREAD

**Issue by miiiingi** [miiiingi/VEDA_MiniProject1#7]
## 기능 구현
- [ ] customerManager가 customer 에 대한 CRUD 작성
- [ ] customer에 대한 point 멤버 변수 추가하고 그것에 대한 getter, setter 구현
- [ ] Item에 대해서 상품 구매(feat, customer point 멤버와 item price 멤버를 이용한)

## 테스트 케이스
- [ ]
- [ ]

**Comment by ajoa2757** [comment]
@miiiingi  

main 또는 로컬 브랜치에 대해서, item 의 구매 동작 코드는 구현은 해 놓겠으나 주석처리 해 둔 채로 push 하겠습니다.(아직 구현되지 않은 item 의 int/uint 멤버 price 와 연관된 함수는 빌드가 불가할 것이므로)
